import { WorkspaceData } from "../types";
export const initialData: WorkspaceData = {
  projects: [
    {
      id: "cedar-residence",
      name: "Cedar Residence",
      description:
        "Modern high-rise residential living featuring panoramic Mediterranean vistas and prime urban connectivity.",
      location: "Beirut, Lebanon",
      startDate: "2026-05-15",
      endDate: "2027-12-30",
      budget: 500000,
      currency: "USD",
      status: "IN_PROGRESS",
      progress: 65,
      paid: 180000,
      units: 12,
      buildings: 2,
      image: "/images/7e935d160931.webp",
    },
    {
      id: "harbor-view",
      name: "Harbor View Towers",
      description:
        "Waterfront luxury living balancing coastal architecture with rigorous engineering standards.",
      location: "Sidon, Lebanon",
      startDate: "2026-10-01",
      endDate: "2028-03-30",
      budget: 720000,
      currency: "USD",
      status: "PLANNING",
      progress: 15,
      paid: 45000,
      units: 18,
      buildings: 1,
      image: "/images/af0735c4125b.webp",
    },
    {
      id: "green-heights",
      name: "Green Heights",
      description:
        "Eco-conscious luxury residences nestled in quiet residential hilltops with private landscaped grounds.",
      location: "Beirut, Lebanon",
      startDate: "2024-01-01",
      endDate: "2026-02-28",
      budget: 650000,
      currency: "USD",
      status: "COMPLETED",
      progress: 100,
      paid: 650000,
      units: 8,
      buildings: 1,
      image: "/images/0432b2fe1fcf.webp",
    },
    {
      id: "pine-ridge",
      name: "Pine Ridge Estates",
      description:
        "Private residences set in the green hills of Mount Lebanon.",
      location: "Mount Lebanon",
      startDate: "2025-08-01",
      endDate: "2027-11-30",
      budget: 850000,
      currency: "USD",
      status: "IN_PROGRESS",
      progress: 45,
      paid: 380000,
      units: 14,
      buildings: 3,
      image: "/images/8f9df9eafeff.webp",
    },
    {
      id: "achrafieh",
      name: "Achrafieh Modern Living",
      description: "Contemporary homes in the heart of Beirut.",
      location: "Beirut, Lebanon",
      startDate: "2025-11-01",
      endDate: "2027-06-30",
      budget: 420000,
      currency: "USD",
      status: "IN_PROGRESS",
      progress: 50,
      paid: 210000,
      units: 6,
      buildings: 1,
      image: "/images/3c4fbca32615.webp",
    },
    {
      id: "verdun",
      name: "Verdun Commercial Hub",
      description: "A new commercial destination for growing businesses.",
      location: "Verdun, Beirut",
      startDate: "2026-02-01",
      endDate: "2028-07-31",
      budget: 1200000,
      currency: "USD",
      status: "IN_PROGRESS",
      progress: 12,
      paid: 150000,
      units: 24,
      buildings: 2,
      image: "/images/2529bf9d2e1d.webp",
    },
  ],
  apartments: [
    {
      id: "apt-201",
      number: "201",
      projectId: "cedar-residence",
      buildingId: "building-a",
      floorId: "floor-2",
      description:
        "Three-bedroom apartment with open living area and eastern-facing balcony. Natural cross-ventilation and custom walnut cabinetry.",
      area: 125,
      bedrooms: 3,
      bathrooms: 2,
      price: 145000,
      currency: "USD",
      status: "AVAILABLE",
      isPublic: true,
      image: "/images/33b403bb7596.webp",
    },
    {
      id: "apt-301",
      number: "301",
      projectId: "cedar-residence",
      buildingId: "building-a",
      floorId: "floor-3",
      description:
        "Elevated sea exposure, premium acoustic insulation, and integrated thermal glass.",
      area: 138,
      bedrooms: 3,
      bathrooms: 2,
      price: 158000,
      currency: "USD",
      status: "AVAILABLE",
      isPublic: true,
      image: "/images/2c9c51213b01.webp",
    },
    {
      id: "apt-104",
      number: "104",
      projectId: "harbor-view",
      buildingId: "tower-1",
      floorId: "harbor-floor-1",
      description:
        "Boutique waterfront apartment with private entry hall and open-concept kitchen.",
      area: 110,
      bedrooms: 2,
      bathrooms: 2,
      price: 128000,
      currency: "USD",
      status: "AVAILABLE",
      isPublic: true,
      image: "/images/e8e4de9f03f9.webp",
    },
    {
      id: "apt-402",
      number: "402",
      projectId: "cedar-residence",
      buildingId: "building-b",
      floorId: "floor-b4",
      description: "Spacious family residence overlooking the city skyline.",
      area: 180,
      bedrooms: 4,
      bathrooms: 3,
      price: 225000,
      currency: "USD",
      status: "RESERVED",
      isPublic: true,
      image: "/images/ff60eafabf8f.webp",
    },
    {
      id: "apt-101",
      number: "101",
      projectId: "cedar-residence",
      buildingId: "building-a",
      floorId: "floor-1",
      description: "Garden residence with an expansive outdoor terrace.",
      area: 95,
      bedrooms: 2,
      bathrooms: 1,
      price: 115000,
      currency: "USD",
      status: "SOLD",
      isPublic: false,
      image: "/images/b05d1000e56e.webp",
    },
    {
      id: "apt-501",
      number: "501",
      projectId: "cedar-residence",
      buildingId: "building-a",
      floorId: "floor-5",
      description: "Private penthouse with panoramic marine views.",
      area: 240,
      bedrooms: 4,
      bathrooms: 4,
      price: 340000,
      currency: "USD",
      status: "AVAILABLE",
      isPublic: true,
      image: "/images/bbc8c5cdcca9.webp",
    },
  ],
  buildings: [
    {
      id: "building-a",
      projectId: "cedar-residence",
      name: "Building A",
      description: "North residential block",
    },
    {
      id: "building-b",
      projectId: "cedar-residence",
      name: "Building B",
      description: "South residential block",
    },
    {
      id: "tower-1",
      projectId: "harbor-view",
      name: "Tower 1",
      description: "Waterfront tower",
    },
  ],
  floors: [
    {
      id: "floor-1",
      buildingId: "building-a",
      name: "Floor 1",
      number: 1,
      description: "",
    },
    {
      id: "floor-2",
      buildingId: "building-a",
      name: "Floor 2",
      number: 2,
      description: "",
    },
    {
      id: "floor-3",
      buildingId: "building-a",
      name: "Floor 3",
      number: 3,
      description: "",
    },
    {
      id: "floor-5",
      buildingId: "building-a",
      name: "Floor 5",
      number: 5,
      description: "Penthouse",
    },
    {
      id: "floor-b4",
      buildingId: "building-b",
      name: "Floor 4",
      number: 4,
      description: "",
    },
    {
      id: "harbor-floor-1",
      buildingId: "tower-1",
      name: "Floor 1",
      number: 1,
      description: "",
    },
  ],
  stages: [
    "Excavation",
    "Foundations",
    "Structure",
    "Electrical",
    "Plumbing",
    "Finishing",
  ].map((name, i) => ({
    id: "stage-" + (i + 1),
    projectId: "cedar-residence",
    name,
    description:
      i === 2
        ? "Structural concrete works covering columns, slabs, beams, staircases, and core elements across Building A and Building B."
        : "Construction scope for " + name.toLowerCase() + ".",
    order: i + 1,
    startDate: [
      "2026-01-10",
      "2026-03-22",
      "2026-05-15",
      "2026-12-01",
      "2027-01-15",
      "2027-04-01",
    ][i],
    endDate: [
      "2026-03-20",
      "2026-05-10",
      "2026-11-30",
      "2027-02-28",
      "2027-04-15",
      "2027-08-30",
    ][i],
    status: i < 2 ? "COMPLETED" : i === 2 ? "IN_PROGRESS" : "NOT_STARTED",
    progress: i < 2 ? 100 : i === 2 ? 58 : 0,
  })),
  tasks: [
    {
      id: "task-1",
      title: "Install Third Floor Reinforcement",
      description:
        "Install reinforcement steel for the third-floor slab and supporting beams in accordance with Cadastral Blueprint A-201.",
      stageId: "stage-3",
      assignee: "Omar Saleh",
      startDate: "2026-09-05",
      endDate: "2026-09-14",
      progress: 65,
      status: "IN_PROGRESS",
      notes: "Prepare eastern section before final reinforcement inspection.",
    },
    {
      id: "task-2",
      title: "Prepare Column Formwork",
      description: "Verify formwork alignment along Grid 3.",
      stageId: "stage-3",
      assignee: "Maya Haddad",
      startDate: "2026-09-12",
      endDate: "2026-09-20",
      progress: 40,
      status: "IN_PROGRESS",
      notes: "",
    },
    {
      id: "task-3",
      title: "Core Wall Steel Placement",
      description: "Place and tie core wall reinforcement.",
      stageId: "stage-3",
      assignee: "Omar Saleh",
      startDate: "2026-09-18",
      endDate: "2026-09-28",
      progress: 20,
      status: "IN_PROGRESS",
      notes: "",
    },
    {
      id: "task-4",
      title: "Concrete Pouring Ground Columns",
      description: "Slab pour completed and cured.",
      stageId: "stage-3",
      assignee: "Omar Saleh",
      startDate: "2026-09-01",
      endDate: "2026-09-10",
      progress: 100,
      status: "COMPLETED",
      notes: "",
    },
    {
      id: "task-5",
      title: "Beam Pre-stressing Verification",
      description: "Inspect beam pre-stressing before sign-off.",
      stageId: "stage-3",
      assignee: "Maya Haddad",
      startDate: "2026-09-25",
      endDate: "2026-10-05",
      progress: 0,
      status: "NOT_STARTED",
      notes: "",
    },
  ],
  parties: [
    {
      id: "abc",
      name: "ABC Construction",
      type: "CONTRACTOR",
      phone: "+961 1 555 210",
      email: "contact@abcconstruction.com",
      address: "Beirut, Lebanon",
      notes: "Primary structural contractor for Cedar Residence.",
    },
    {
      id: "materials",
      name: "Cedars Building Materials",
      type: "SUPPLIER",
      phone: "+961 7 222 410",
      email: "sales@cedarsmaterials.com",
      address: "Sidon, Lebanon",
      notes: "Bulk cement and building materials.",
    },
    {
      id: "electrical",
      name: "Lebanon Electrical Works",
      type: "CONTRACTOR",
      phone: "+961 3 411 728",
      email: "office@lew.com",
      address: "Beirut, Lebanon",
      notes: "Electrical installations and high voltage panels.",
    },
    {
      id: "plumbing",
      name: "Beirut Modern Plumbing",
      type: "CONTRACTOR",
      phone: "+961 1 789 012",
      email: "contact@beirutplumbing.lb",
      address: "Beirut, Lebanon",
      notes: "Plumbing and MEP subcontractor.",
    },
    {
      id: "aggregates",
      name: "Mount Lebanon Aggregates",
      type: "SUPPLIER",
      phone: "+961 5 921 340",
      email: "orders@mt-aggregates.com",
      address: "Mount Lebanon",
      notes: "Crushed stone and sand.",
    },
    {
      id: "geotech",
      name: "Geotechnical Testing Lab",
      type: "OTHER",
      phone: "+961 1 334 556",
      email: "info@geotech-lab.lb",
      address: "Achrafieh, Beirut",
      notes: "Soil boring and core sampling.",
    },
  ],
  categories: [
    "Materials",
    "Labor",
    "Electrical",
    "Plumbing",
    "Painting",
    "Other",
  ].map((name, i) => ({
    id: "cat-" + i,
    name,
    description: [
      "Construction materials, concrete, steel, and site supplies",
      "Site labor, contractor execution, and specialized trades",
      "Electrical installations, wiring, conduits, and panels",
      "Plumbing installation, piping, risers, and sanitary systems",
      "Interior/exterior painting, finishes, and protective coatings",
      "Miscellaneous construction expenses and municipal permits",
    ][i],
  })),
  payments: [
    {
      id: "pay-014",
      projectId: "cedar-residence",
      partyId: "abc",
      categoryId: "cat-1",
      amount: 8500,
      currency: "USD",
      date: "2026-09-12",
      reference: "CR-PAY-014",
      description:
        "Structural labor payment for third-floor reinforcement works. Inspection verified by site engineer.",
    },
    {
      id: "pay-013",
      projectId: "cedar-residence",
      partyId: "materials",
      categoryId: "cat-0",
      amount: 6200,
      currency: "USD",
      date: "2026-09-10",
      reference: "CR-PAY-013",
      description: "Concrete, aggregates and steel supplies.",
    },
    {
      id: "pay-012",
      projectId: "cedar-residence",
      partyId: "electrical",
      categoryId: "cat-2",
      amount: 3750,
      currency: "USD",
      date: "2026-09-06",
      reference: "CR-PAY-012",
      description: "Electrical rough-in installation.",
    },
    {
      id: "pay-009",
      projectId: "cedar-residence",
      partyId: "abc",
      categoryId: "cat-0",
      amount: 10000,
      currency: "USD",
      date: "2026-09-02",
      reference: "CR-PAY-009",
      description: "Structural reinforcement supply.",
    },
    {
      id: "pay-008",
      projectId: "cedar-residence",
      partyId: "plumbing",
      categoryId: "cat-3",
      amount: 4300,
      currency: "USD",
      date: "2026-08-28",
      reference: "CR-PAY-008",
      description: "Plumbing risers and pipe installation.",
    },
    {
      id: "pay-004",
      projectId: "harbor-view",
      partyId: "materials",
      categoryId: "cat-0",
      amount: 15000,
      currency: "USD",
      date: "2026-08-21",
      reference: "HV-PAY-004",
      description: "Materials for waterfront foundations.",
    },
  ],
  leads: [
    {
      id: "lead-1",
      name: "Ahmad Khalil",
      email: "ahmad@example.com",
      phone: "+961 70 123 456",
      apartmentId: "apt-201",
      status: "NEW",
      message:
        "I am interested in Apartment 201 at Cedar Residence and would like more information about the total selling price, payment schedule, and expected structural completion date. Is parking allocated?",
      date: "2026-09-15",
      notes: [
        "Assigned to sales executive Rami Khalil. Client requires clarification on payment milestones.",
      ],
    },
    {
      id: "lead-2",
      name: "Sarah Mansour",
      email: "sarah@example.com",
      phone: "+961 3 444 901",
      apartmentId: "apt-301",
      status: "CONTACTED",
      message: "Interested in a residence with sea views.",
      date: "2026-09-14",
      notes: [],
    },
    {
      id: "lead-3",
      name: "Rami Nasser",
      email: "rnasser@finances.org",
      phone: "+961 71 890 234",
      apartmentId: "apt-104",
      status: "NEW",
      message: "Please send availability and floor plan.",
      date: "2026-09-10",
      notes: [],
    },
    {
      id: "lead-4",
      name: "Dr. Ziad Abboud",
      email: "z.abboud@example.com",
      phone: "+961 76 543 210",
      apartmentId: "apt-301",
      status: "CLOSED",
      message: "High floor request.",
      date: "2026-09-08",
      notes: [],
    },
    {
      id: "lead-5",
      name: "Lina El-Khoury",
      email: "lina@example.com",
      phone: "+961 1 789 654",
      apartmentId: "apt-402",
      status: "CONTACTED",
      message: "Looking for a family residence.",
      date: "2026-09-05",
      notes: [],
    },
  ],
  documents: [
    "Construction Agreement.pdf",
    "Architectural Plan - Floor 2.pdf",
    "Building Permit #BP-2025-09.pdf",
    "Structural Calculation Model.dwg",
    "Geotechnical Site Soil Notes.docx",
    "Concrete Pour Sign-off Inspection.pdf",
  ].map((name, i) => ({
    id: "doc-" + i,
    projectId: "cedar-residence",
    name,
    category: (
      ["Agreement", "Plan", "Permit", "Plan", "Other", "Other"] as const
    )[i],
    format: name.split(".").pop()!.toUpperCase(),
    size: ["3.4 MB", "12.8 MB", "1.8 MB", "24.1 MB", "850 KB", "2.1 MB"][i],
    date: "2026-09-" + String(10 - i).padStart(2, "0"),
  })),
  members: [
    {
      id: "omar",
      name: "Omar Saleh",
      email: "omar@cedarconstruction.com",
      role: "PROJECT_MANAGER",
      active: true,
      platformRole: "USER",
    },
    {
      id: "maya",
      name: "Maya Haddad",
      email: "maya@cedarconstruction.com",
      role: "SITE_ENGINEER",
      active: true,
      platformRole: "USER",
    },
    {
      id: "rami",
      name: "Rami Khalil",
      email: "rami@cedarconstruction.com",
      role: "SALES",
      active: true,
      platformRole: "USER",
    },
    {
      id: "nour",
      name: "Nour Hassan",
      email: "nour@cedarconstruction.com",
      role: "FINANCE",
      active: true,
      platformRole: "USER",
    },
    {
      id: "hamza",
      name: "Hamza Merhi",
      email: "hamza@example.com",
      role: "OWNER",
      active: true,
      platformRole: "SUPER_ADMIN",
    },
  ],
  companies: [
    {
      id: "cedar",
      name: "Cedar Construction",
      email: "info@cedarconstruction.com",
      phone: "+961 1 555 220",
      address: "Plot 4412, Port District, Beirut, Lebanon",
      category: "General Contractor & Property Development",
      active: true,
    },
    {
      id: "atlas",
      name: "Atlas Engineering",
      email: "info@atlas.com.lb",
      phone: "+961 1 420 100",
      address: "Beirut, Lebanon",
      category: "Structural Contracting",
      active: true,
    },
    {
      id: "coastal",
      name: "Coastal Developments",
      email: "hello@coastal.lb",
      phone: "+961 7 220 500",
      address: "Sidon, Lebanon",
      category: "Property Developer",
      active: false,
    },
  ],
  updates: [
    {
      id: "update-1",
      taskId: "task-1",
      progress: 65,
      notes:
        "Reinforcement on the eastern section completed. Tension bars tied and verified against specs.",
      date: "2026-09-19T10:45:00",
      photo: "/images/5e095b5946b0.webp",
    },
    {
      id: "update-2",
      taskId: "task-1",
      progress: 50,
      notes: "Main reinforcement grid installed across bays 1 through 4.",
      date: "2026-09-13T15:20:00",
    },
    {
      id: "update-3",
      taskId: "task-1",
      progress: 30,
      notes: "Initial reinforcement placement started by sub-team.",
      date: "2026-09-12T09:10:00",
    },
  ],
  land: {
    area: 1000,
    parcel: "LB-BEI-4412",
    maxHeight: 20,
    ratio: 60,
    constraints:
      "Residential zoning. Maintain statutory setbacks and municipal height limits.",
    notes: "Verify against Cadastral Document LB-4412-A.",
  },
  profile: {
    name: "Omar Saleh",
    email: "omar@cedarconstruction.com",
    phone: "+961 70 123 456",
  },
};
