'use client';
import { useState } from 'react';
import { useWorkspace } from './WorkspaceProvider';
import { PageHeader,StatCard,Badge,Panel,TextLink,EmptyState,DetailList } from '../ui/Primitives';
import { DataTable } from '../ui/DataTable';
import { Dialog,ConfirmDialog } from '../ui/Dialog';
import { PlatformRoleForm } from '../forms/AccountForms';
export function PlatformDashboard(){const {data}=useWorkspace();return <><PageHeader title="Platform Dashboard" eyebrow="Platform Administration" description="Monitor companies, users, and the overall platform workspace registry."/><div className="stats"><StatCard label="Total Companies" value={data.companies.length}/><StatCard label="Active Companies" value={data.companies.filter(c=>c.active).length}/><StatCard label="Platform Users" value={data.members.length}/><StatCard label="Super Admins" value={data.members.filter(m=>m.platformRole==='SUPER_ADMIN').length}/></div><div className="stack"><Panel title="Recently Added Companies" action={<TextLink href="/platform/companies">View Companies</TextLink>}><CompaniesTable/></Panel><Panel title="Recent Platform Users" action={<TextLink href="/platform/users">View Users</TextLink>}><PlatformUsers compact/></Panel></div></>;}
function CompaniesTable(){const {data}=useWorkspace();const [status,setStatus]=useState('');return <DataTable rows={data.companies.filter(c=>!status||String(c.active)===status)} searchText={c=>c.name+' '+c.email+' '+c.category} placeholder="Search companies by name, email, or category…" filters={<select aria-label="Company status" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All Statuses</option><option value="true">Active</option><option value="false">Inactive</option></select>} columns={[{label:'Company Workspace',value:c=><strong>{c.name}</strong>,sort:c=>c.name},{label:'Category',value:c=>c.category},{label:'Contact Email',value:c=>c.email},{label:'Phone',value:c=>c.phone},{label:'Status',value:c=><Badge value={c.active?'Active':'Inactive'}/>},{label:'Actions',value:c=><TextLink href={'/platform/companies/'+c.id}>View</TextLink>}]}/>;}
export function PlatformCompanies(){return <><PageHeader title="Companies" description="Centralized supervision of company workspaces and platform access."/><CompaniesTable/></>;}
export function PlatformCompanyDetail({id}:{id:string}){const {data,save,notify}=useWorkspace();const [confirm,setConfirm]=useState(false);const company=data.companies.find(c=>c.id===id);if(!company)return <EmptyState title="Company not found"/>;return <><PageHeader title={company.name} description={company.category} back="/platform/companies"><Badge value={company.active?'Active':'Inactive'}/><button className={'button '+(company.active?'destructive':'')} onClick={()=>setConfirm(true)}>{company.active?'Deactivate':'Activate'} Company</button></PageHeader><div className="two-column"><div className="stack"><Panel title="Company Information"><DetailList items={[["Company",company.name],['Category',company.category],['Contact Email',company.email],['Phone',company.phone],['Address',company.address]]}/></Panel><Panel title="Company Members">{id==='cedar'?<DataTable rows={data.members} searchText={m=>m.name} columns={[{label:'Member',value:m=>m.name},{label:'Corporate Email',value:m=>m.email},{label:'Tenant Role',value:m=><Badge value={m.role}/>},{label:'Status',value:m=><Badge value={m.active?'Active':'Inactive'}/>}]}/>:<EmptyState title="No members registered" description="No members are included for this company in the demo dataset."/>}</Panel></div><Panel title="Platform Governance"><DetailList items={[["Tenant Identifier",id],['Platform Status',company.active?'Active':'Inactive'],['Company Category',company.category]]}/><p className="form-note">Company access controls are demonstrated using local state. This frontend does not enforce backend authorization.</p></Panel></div><ConfirmDialog open={confirm} onClose={()=>setConfirm(false)} title={company.active?'Deactivate Company?':'Activate Company?'} description={'Update the platform status of '+company.name+'?'} onConfirm={()=>{save('companies',{...company,active:!company.active});notify('Company platform status updated.');}}/></>;}
export function PlatformUsers({compact=false}:{compact?:boolean}){const {data,save,notify}=useWorkspace();const [editing,setEditing]=useState('');const [role,setRole]=useState('');const [status,setStatus]=useState('');return <>{!compact&&<PageHeader title="Users" description="Manage platform identity roles and active status across company workspaces."/>}<DataTable rows={data.members.filter(m=>(!role||m.platformRole===role)&&(!status||String(m.active)===status))} searchText={m=>m.name+' '+m.email} filters={<><select aria-label="Platform role" value={role} onChange={e=>setRole(e.target.value)}><option value="">All Roles</option><option>USER</option><option>SUPER_ADMIN</option></select><select aria-label="User status" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All Statuses</option><option value="true">Active</option><option value="false">Inactive</option></select></>} columns={[{label:'User',value:m=><strong>{m.name}</strong>,sort:m=>m.name},{label:'Email Address',value:m=>m.email},{label:'Platform Role',value:m=><Badge value={m.platformRole}/>},{label:'Status',value:m=><Badge value={m.active?'Active':'Inactive'}/>},{label:'Primary Workspace',value:()=> 'Cedar Construction'},{label:'Actions',value:m=><div className="row-actions"><button onClick={()=>setEditing(m.id)}>Change Role</button><button onClick={()=>{save('members',{...m,active:!m.active});notify('User status updated.');}}>{m.active?'Deactivate':'Activate'}</button></div>}]}/>{!compact&&<div className="form-note">Platform roles control administration access. Company roles independently describe each user’s responsibilities within their workspace.</div>}<Dialog open={!!editing} onClose={()=>setEditing('')} title="Change Platform Role">{editing&&<PlatformRoleForm key={editing} id={editing} onClose={()=>setEditing('')}/>}</Dialog></>;}
