'use client';
import { useForm,FormProvider } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { useRouter } from 'next/navigation';
import { partySchema } from '@/lib/validations/party.schema';
import { paymentSchema } from '@/lib/validations/payment.schema';
import { categorySchema } from '@/lib/validations/payment-category.schema';
import { documentSchema } from '@/lib/validations/document.schema';
import { leadSchema,noteSchema } from '@/lib/validations/lead.schema';
import { useWorkspace } from '../features/WorkspaceProvider';
import { PageHeader } from '../ui/Primitives';
import { Field,Textarea,FormSection,FormActions } from './FormPrimitives';
export function PartyForm({id}:{id?:string}){const {data,save,notify}=useWorkspace();const router=useRouter();const form=useForm<z.input<typeof partySchema>,unknown,z.output<typeof partySchema>>({resolver:zodResolver(partySchema),values:data.parties.find(p=>p.id===id),defaultValues:data.parties.find(p=>p.id===id)??{name:'',type:'CONTRACTOR',phone:'',email:'',address:'',notes:''}});return <div className="form-layout"><PageHeader title={id?'Edit Party':'Add Party'} description="Register an external contractor, supplier, or project partner." back="/app/parties"/><FormProvider {...form}><form noValidate onSubmit={form.handleSubmit(v=>{const key=id??crypto.randomUUID();save('parties',{...v,id:key});notify('Party saved successfully.');router.push('/app/parties/'+key);})}><FormSection title="1. Party Information"><Field name="name" label="Company / Entity Legal Name *"/><Field name="type" label="Party Category *"><option value="CONTRACTOR">Contractor — On-site execution</option><option value="SUPPLIER">Supplier — Procurement logistics</option><option value="OTHER">Other — Consulting & quality</option></Field><Textarea name="notes" label="Notes & Operational Brief"/></FormSection><FormSection title="2. Contact & Address"><div className="form-grid"><Field name="phone" label="Phone Number *" type="tel"/><Field name="email" label="Email Address *" type="email"/></div><Textarea name="address" label="Physical or Depot Address"/></FormSection><FormActions onCancel={()=>router.push('/app/parties')} label={id?'Save Changes':'Add Party'}/></form></FormProvider></div>;}
export function PaymentForm({id}:{id?:string}){const {data,save,notify}=useWorkspace();const router=useRouter();const form=useForm<z.input<typeof paymentSchema>,unknown,z.output<typeof paymentSchema>>({resolver:zodResolver(paymentSchema),values:data.payments.find(p=>p.id===id),defaultValues:data.payments.find(p=>p.id===id)??{projectId:'cedar-residence',partyId:'abc',categoryId:'cat-1',amount:'',currency:'USD',date:'2026-09-19',reference:'',description:''}});return <div className="form-layout"><PageHeader title={id?'Edit Payment':'Record Payment'} description="Add an outgoing payment made for a construction project." back="/app/payments"/><FormProvider {...form}><form noValidate onSubmit={form.handleSubmit(v=>{const key=id??crypto.randomUUID();save('payments',{...v,id:key});notify('Payment recorded successfully. Reference: '+v.reference);router.push('/app/payments/'+key);})}><FormSection title="01 / Scope"><Field name="projectId" label="Project *">{data.projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</Field></FormSection><FormSection title="02 / Beneficiary"><Field name="partyId" label="Party *">{data.parties.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</Field></FormSection><FormSection title="03 / Categorization"><Field name="categoryId" label="Payment Category *">{data.categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</Field></FormSection><FormSection title="04 / Financial Valuation"><div className="form-grid"><Field name="currency" label="Currency *"><option>USD</option><option>EUR</option><option>LBP</option></Field><Field name="amount" label="Disbursement Amount *" type="number" step="any"/></div></FormSection><FormSection title="05 / Audit & Reference"><div className="form-grid"><Field name="date" label="Payment Date *" type="date"/><Field name="reference" label="Reference *" placeholder="e.g. CR-PAY-015"/></div></FormSection><FormSection title="06 / Scope & Purpose"><Textarea name="description" label="Description"/></FormSection><FormActions onCancel={()=>router.push('/app/payments')} label={id?'Save Changes':'Record Payment'}/></form></FormProvider></div>;}
export function CategoryForm({id,onClose}:{id?:string;onClose:()=>void}){const {data,save,notify}=useWorkspace();const form=useForm<z.input<typeof categorySchema>,unknown,z.output<typeof categorySchema>>({resolver:zodResolver(categorySchema),values:data.categories.find(c=>c.id===id),defaultValues:data.categories.find(c=>c.id===id)??{name:'',description:''}});return <FormProvider {...form}><form noValidate onSubmit={form.handleSubmit(v=>{save('categories',{...v,id:id??crypto.randomUUID()});notify('Payment category saved.');onClose();})}><Field name="name" label="Category Name *"/><div className="section-space"><Textarea name="description" label="Description"/></div><FormActions onCancel={onClose} label={id?'Save Changes':'Add Category'}/></form></FormProvider>;}
export function LeadStatusForm({id,onClose}:{id:string;onClose:()=>void}){const {data,save,notify}=useWorkspace();const lead=data.leads.find(l=>l.id===id)!;const form=useForm<z.input<typeof leadSchema>,unknown,z.output<typeof leadSchema>>({resolver:zodResolver(leadSchema),defaultValues:{status:lead.status,note:''}});return <FormProvider {...form}><form noValidate onSubmit={form.handleSubmit(v=>{save('leads',{...lead,status:v.status,notes:v.note?[v.note,...lead.notes]:lead.notes});notify('Lead status updated successfully.');onClose();})}><div className="form-note">{lead.name} · Current status: {lead.status}</div><Field name="status" label="Select New Status *"><option value="NEW">New — Awaiting initial sales contact</option><option value="CONTACTED">Contacted — Communication established</option><option value="CLOSED">Closed — Enquiry concluded</option></Field><div className="section-space"><Textarea name="note" label="Follow-up Note (Optional)"/></div><FormActions onCancel={onClose} label="Save Status"/></form></FormProvider>;}
export function LeadNoteForm({id,onClose}:{id:string;onClose:()=>void}){const {data,save,notify}=useWorkspace();const form=useForm<z.infer<typeof noteSchema>>({resolver:zodResolver(noteSchema),defaultValues:{note:''}});return <FormProvider {...form}><form noValidate onSubmit={form.handleSubmit(v=>{const lead=data.leads.find(l=>l.id===id)!;save('leads',{...lead,notes:[v.note,...lead.notes]});notify('Follow-up note added.');onClose();})}><Textarea name="note" label="Record Follow-up Interaction"/><FormActions onCancel={onClose} label="Save Log"/></form></FormProvider>;}
export function DocumentForm({onClose}:{onClose?:()=>void}){const {data,save,notify}=useWorkspace();const router=useRouter();const close=onClose??(()=>router.push('/app/documents'));const form=useForm<z.input<typeof documentSchema>,unknown,z.output<typeof documentSchema>>({resolver:zodResolver(documentSchema),defaultValues:{projectId:'cedar-residence',name:'',category:'Plan'}});return <FormProvider {...form}><form noValidate className="stack" onSubmit={form.handleSubmit(v=>{const file=v.file[0];save('documents',{id:crypto.randomUUID(),projectId:v.projectId,name:v.name,category:v.category,format:file.name.split('.').pop()!.toUpperCase(),size:(file.size/1024/1024).toFixed(1)+' MB',date:new Date().toISOString().slice(0,10),url:URL.createObjectURL(file)});notify('Document added to the local project registry.');close();})}><Field name="projectId" label="Project *">{data.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</Field><Field name="name" label="Document Name *" placeholder="e.g. Building Permit — Revision 2"/><Field name="category" label="Category *"><option>Agreement</option><option>Plan</option><option>Permit</option><option>Other</option></Field><Field name="file" label="File Attachment *" type="file" accept=".pdf,.docx,.dwg,.xlsx,.png" hint="Supports PDF, DOCX, DWG, XLSX, PNG (Max 50MB)"/><div className="form-note">Files remain in this browser session. No upload service is connected.</div><FormActions onCancel={close} label="Upload Document"/></form></FormProvider>;}
