'use client';
import { useId,type ReactNode,type InputHTMLAttributes } from 'react';
import { useFormContext } from 'react-hook-form';
export function Field({name,label,children,hint,...props}:{name:string;label:string;children?:ReactNode;hint?:string}&InputHTMLAttributes<HTMLInputElement>){const {register,formState:{errors}}=useFormContext();const id=useId();const error=errors[name]?.message;const aria={'aria-invalid':Boolean(error),'aria-describedby':error?id+'-error':hint?id+'-hint':undefined};return <div className="field"><label htmlFor={id}>{label}</label>{children?<select id={id} {...register(name)} {...aria}>{children}</select>:<input id={id} {...register(name)} {...props} {...aria}/ >}{hint&&<small id={id+'-hint'}>{hint}</small>}{error&&<p className="field-error" id={id+'-error'}>{String(error)}</p>}</div>;}
export function Textarea({name,label,placeholder}:{name:string;label:string;placeholder?:string}){const {register,formState:{errors}}=useFormContext();const id=useId();return <div className="field"><label htmlFor={id}>{label}</label><textarea id={id} rows={4} placeholder={placeholder} {...register(name)} aria-invalid={Boolean(errors[name])} aria-describedby={errors[name]?id+'-error':undefined}/>{errors[name]&&<p className="field-error" id={id+'-error'}>{String(errors[name]?.message)}</p>}</div>;}
export function CheckField({name,label}:{name:string;label:string}){const {register,formState:{errors}}=useFormContext();const id=useId();return <div className="field"><label className="check-field" htmlFor={id}><input id={id} type="checkbox" {...register(name)} aria-invalid={Boolean(errors[name])} aria-describedby={errors[name]?id+'-error':undefined}/>{label}</label>{errors[name]&&<p id={id+'-error'} className="field-error">{String(errors[name]?.message)}</p>}</div>;}
export function FormSection({title,description,children}:{title:string;description?:string;children:ReactNode}){return <section className="form-section"><div className="form-section-title"><h2>{title}</h2>{description&&<p>{description}</p>}</div><div className="form-section-content">{children}</div></section>;}

/** Shared numbered section shell (design source: apartment form hierarchy). */
export function NumberedSection({number,title,micro,description,children}:{number:string|number;title:string;micro?:string;description?:string;children:ReactNode}){return <section className="form-section"><div className="apt-sec-head"><span className="apt-num" aria-hidden="true">{number}</span><div style={{flex:1}}><h2>{title}</h2>{description&&<p>{description}</p>}</div>{micro&&<span className="apt-micro">{micro}</span>}</div><div className="form-section-content">{children}</div></section>;}
export function FormActions({pending,label='Save Changes',onCancel}:{pending?:boolean;label?:string;onCancel:()=>void}){return <div className="form-actions"><button type="button" className="button secondary" onClick={onCancel}>Cancel</button><button type="submit" className="button" disabled={pending}>{pending?'Saving…':label}</button></div>;}
