"""create company party table 2 

Revision ID: 354d160db13b
Revises: ac521165efa5
Create Date: 2026-09-20 22:41:43.791809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '354d160db13b'
down_revision: Union[str, Sequence[str], None] = 'ac521165efa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_parties',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('party_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('CONTRACTOR', 'SUPPLIER', 'CONSULTANT', 'OTHER', name='partyrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'party_id', 'role', name='uq_company_party_role')
    )
    op.create_index(op.f('ix_company_parties_company_id'), 'company_parties', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_parties_party_id'), 'company_parties', ['party_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_parties_party_id'), table_name='company_parties')
    op.drop_index(op.f('ix_company_parties_company_id'), table_name='company_parties')
    op.drop_table('company_parties')
    # ### end Alembic commands ###
