"""remove company party table

Revision ID: 413b8fb26470
Revises: 354d160db13b
Create Date: 2026-09-21 01:20:31.846716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '413b8fb26470'
down_revision: Union[str, Sequence[str], None] = '354d160db13b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_parties_company_id'), table_name='company_parties')
    op.drop_index(op.f('ix_company_parties_party_id'), table_name='company_parties')
    op.drop_table('company_parties')
    op.add_column('tasks', sa.Column('party_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_tasks_party_id'), 'tasks', ['party_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'parties', ['party_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_party_id'), table_name='tasks')
    op.drop_column('tasks', 'party_id')
    op.create_table('company_parties',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('party_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('CONTRACTOR', 'SUPPLIER', 'CONSULTANT', 'OTHER', name='partyrole'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('company_parties_company_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], name=op.f('company_parties_party_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('company_parties_pkey')),
    sa.UniqueConstraint('company_id', 'party_id', 'role', name=op.f('uq_company_party_role'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_company_parties_party_id'), 'company_parties', ['party_id'], unique=False)
    op.create_index(op.f('ix_company_parties_company_id'), 'company_parties', ['company_id'], unique=False)
    # ### end Alembic commands ###
