"""update partyTypes1

Revision ID: 7af45c655d4e
Revises: b53f05237879
Create Date: 2026-09-21 11:03:02.308648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7af45c655d4e'
down_revision: Union[str, Sequence[str], None] = 'b53f05237879'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parties', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parties', sa.Column('type', postgresql.ENUM('PERSON', 'ORGANIZATION', name='partytype'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
