"""update project schema remove currancy

Revision ID: 883943f24f48
Revises: a83dcb8c4b2a
Create Date: 2026-09-17 13:11:49.129002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '883943f24f48'
down_revision: Union[str, Sequence[str], None] = 'a83dcb8c4b2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'currency')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
