"""update constrution and project 

Revision ID: 9d98762d3722
Revises: 9a86de3773e3
Create Date: 2026-09-20 22:30:45.265186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d98762d3722'
down_revision: Union[str, Sequence[str], None] = '9a86de3773e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('construction_stages', 'status')
    op.drop_column('projects', 'status')
    op.alter_column('task_updates', 'status',
               existing_type=postgresql.ENUM('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='taskstatus'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_updates', 'status',
               existing_type=postgresql.ENUM('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='taskstatus'),
               nullable=True)
    op.add_column('projects', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('construction_stages', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
