"""update company schema remove category

Revision ID: a83dcb8c4b2a
Revises: 9f851e448d40
Create Date: 2026-09-16 22:44:08.400617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a83dcb8c4b2a'
down_revision: Union[str, Sequence[str], None] = '9f851e448d40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
