"""update partyTypes2

Revision ID: b7952b1bf811
Revises: 7af45c655d4e
Create Date: 2026-09-21 11:04:33.752056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7952b1bf811'
down_revision: Union[str, Sequence[str], None] = '7af45c655d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parties', sa.Column('type', sa.Enum('CONTRACTOR', 'SUPPLIER', name='partytype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parties', 'type')
    # ### end Alembic commands ###
