"""update document add original filename

Revision ID: dbe77dd66939
Revises: ed264c246a19
Create Date: 2026-09-21 22:01:12.701226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dbe77dd66939'
down_revision: Union[str, Sequence[str], None] = 'ed264c246a19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('original_filename', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('documents', 'uploaded_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('documents_uploaded_by_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'users', ['uploaded_by'], ['id'], ondelete='SET NULL')
    op.drop_column('documents', 'uploaded_at')
    op.drop_column('payment_categories', 'description')
    op.drop_column('payments', 'currency')
    op.drop_column('payments', 'reference')
    op.drop_constraint(op.f('tasks_assigned_to_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_assigned_to_fkey'), 'tasks', 'users', ['assigned_to'], ['id'])
    op.add_column('payments', sa.Column('reference', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('payment_categories', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_uploaded_by_fkey'), 'documents', 'users', ['uploaded_by'], ['id'])
    op.alter_column('documents', 'uploaded_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('documents', 'created_at')
    op.drop_column('documents', 'original_filename')
    # ### end Alembic commands ###
