"""create company party table 

Revision ID: fad9e2c41864
Revises: aac06aa674e6
Create Date: 2026-09-20 22:36:56.481947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fad9e2c41864'
down_revision: Union[str, Sequence[str], None] = 'aac06aa674e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('construction_stages', 'status',
               existing_type=postgresql.ENUM('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='constructionstagestatus'),
               nullable=False)
    op.alter_column('projects', 'status',
               existing_type=postgresql.ENUM('PLANNING', 'IN_PROGRESS', 'COMPLETED', 'ON_HOLD', name='projectstatus'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'status',
               existing_type=postgresql.ENUM('PLANNING', 'IN_PROGRESS', 'COMPLETED', 'ON_HOLD', name='projectstatus'),
               nullable=True)
    op.alter_column('construction_stages', 'status',
               existing_type=postgresql.ENUM('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='constructionstagestatus'),
               nullable=True)
    # ### end Alembic commands ###
